DROP TABLE IF EXISTS `RETRYERRORS`;
CREATE TABLE `RETRYERRORS`(
`RETRYERROR_ID` int(10) NOT NULL AUTO_INCREMENT,
`ErrorSource` varchar(256) NOT NULL,
`ErrorCode` int(10) NOT NULL,
`ErrorDiag` varchar(256),
`RETRYACTION` int(10) NOT NULL,
`Parameters` varchar(256),
`Architecture` varchar(256),
`Release` VARCHAR(64),
`WorkQueue_ID` tinyint(5),
`Description` varchar(250),
`Expiration_date` timestamp,
`Active` char NOT NULL default 'Y',
UNIQUE KEY `RETRYERRORS_ID_PRIMARY` (`RETRYERROR_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `CONFIG`;
CREATE TABLE `CONFIG`(
`APP` VARCHAR(64) NOT NULL,
`COMPONENT` VARCHAR(64) NOT NULL,
`KEY`	VARCHAR(64) NOT NULL,
`VALUE` VARCHAR(256) NOT NULL,
`TYPE` VARCHAR(64) NOT NULL,
`VO` VARCHAR(16) DEFAULT NULL,
`DESCR` VARCHAR(256) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `GLOBAL_SHARES`;
CREATE TABLE `GLOBAL_SHARES`(
`NAME` VARCHAR(32) NOT NULL,
`VALUE` TINYINT(3) NOT NULL,
`PARENT` VARCHAR(32) DEFAULT NULL,
`PRODSOURCELABEL` VARCHAR(100) DEFAULT NULL,
`WORKINGGROUP` VARCHAR(100) DEFAULT NULL,
`CAMPAIGN` VARCHAR(100) DEFAULT NULL,
`PROCESSINGTYPE` VARCHAR(100) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `DDM_ENDPOINT`;
CREATE TABLE `DDM_ENDPOINT`(
`DDM_ENDPOINT_NAME` VARCHAR(52) NOT NULL,
`SITE_NAME` VARCHAR(52) DEFAULT NULL,
`DDM_SPACETOKEN_NAME` VARCHAR(52) DEFAULT NULL,
`SPACE_TOTAL` INT(11) DEFAULT NULL,
`SPACE_FREE` INT(11) DEFAULT NULL,
`SPACE_USED` INT(11) DEFAULT NULL,
`IS_TAPE` VARCHAR(1) DEFAULT NULL,
`TYPE` VARCHAR(20) DEFAULT NULL,
`BLACKLISTED` VARCHAR(1)  DEFAULT NULL,
`SPACE_TIMESTAMP` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
`SPACE_EXPIRED` INT(11) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PANDA_SITE`;
CREATE TABLE `PANDA_SITE`(
`PANDA_SITE_NAME` VARCHAR(52) NOT NULL,
`SITE_NAME`	VARCHAR(52) DEFAULT NULL,
`IS_LOCAL`	VARCHAR(1) DEFAULT NULL,
`DEFAULT_DDM_ENDPOINT`	VARCHAR(52) DEFAULT NULL,
`STORAGE_SITE_NAME`	VARCHAR(52) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `SITE`;
CREATE TABLE `SITE`(
`SITE_NAME` VARCHAR(52) NOT NULL,
`ROLE` VARCHAR(256) DEFAULT NULL,
`TIER_LEVEL` TINYINT(1) DEFAULT 2,
`STATE` VARCHAR(52) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `JEDI_TASKS`
ADD COLUMN `TTCREQUESTED` DATE DEFAULT NULL,
ADD COLUMN `TTCPREDICTIONDATE` DATE DEFAULT NULL,
ADD COLUMN `GSHARE` VARCHAR(32) DEFAULT NULL,
ADD COLUMN `RESCUETIME` DATE DEFAULT NULL,
ADD COLUMN `REQUESTTYPE` VARCHAR(32) DEFAULT NULL;

ALTER TABLE `JOBSACTIVE4`
ADD COLUMN `FAILEDATTEMPT` TINYINT(3) DEFAULT NULL,
ADD COLUMN `HS06SEC` INT(11) DEFAULT NULL,
ADD COLUMN `GSHARE` VARCHAR(32) DEFAULT NULL,
ADD COLUMN `HS06` INT(11) DEFAULT 0;

ALTER TABLE `JOBSARCHIVED4`
ADD COLUMN `FAILEDATTEMPT` TINYINT(3) DEFAULT NULL,
ADD COLUMN `HS06SEC` INT(11) DEFAULT NULL,
ADD COLUMN `GSHARE` VARCHAR(32) DEFAULT NULL,
ADD COLUMN `HS06` INT(11) DEFAULT NULL;

ALTER TABLE `JOBSARCHIVED`
ADD COLUMN `FAILEDATTEMPT` TINYINT(3) DEFAULT NULL,
ADD COLUMN `HS06SEC` INT(11) DEFAULT NULL,
ADD COLUMN `GSHARE` VARCHAR(32) DEFAULT NULL,
ADD COLUMN `HS06` INT(11) DEFAULT NULL;

ALTER TABLE `JOBSDEFINED4`
ADD COLUMN `FAILEDATTEMPT` TINYINT(3) DEFAULT NULL,
ADD COLUMN `HS06SEC` INT(11) DEFAULT NULL,
ADD COLUMN `GSHARE` VARCHAR(32) DEFAULT NULL,
ADD COLUMN `HS06` INT(11) DEFAULT 0;

ALTER TABLE `JOBSWAITING4`
ADD COLUMN `FAILEDATTEMPT` TINYINT(3) DEFAULT NULL,
ADD COLUMN `HS06SEC` INT(11) DEFAULT NULL,
ADD COLUMN `GSHARE` VARCHAR(32) DEFAULT NULL,
ADD COLUMN `HS06` INT(11) DEFAULT 0;

ALTER TABLE `SITEDATA`
ADD COLUMN `NOJOB` INT(7) DEFAULT NULL,
ADD COLUMN `GETJOBABS` INT(10) DEFAULT NULL,
ADD COLUMN `UPDATEJOBABS` INT(10) DEFAULT NULL,
ADD COLUMN `NOJOBABS` INT(10) DEFAULT 0;
