import json
import traceback
import uuid

from pandacommon.pandalogger.LogWrapper import LogWrapper
from pandacommon.pandalogger.PandaLogger import PandaLogger

from pandaserver.workflow.data_handler_plugins.base_data_handler import BaseDataHandler
from pandaserver.workflow.workflow_base import (
    WFDataSpec,
    WFDataStatus,
    WFDataTargetCheckResult,
    WFDataTargetCheckStatus,
    WFDataType,
    WFStepSpec,
    WFStepStatus,
    WFStepType,
    WorkflowSpec,
    WorkflowStatus,
)

# Default workflow options for partial data handling
# These defaults are used if not specified in the workflow definition
DEFAULT_ALLOW_PARTIAL_INPUTS = False
DEFAULT_MIN_INPUT_FILES = 10

# main logger
logger = PandaLogger().getLogger(__name__.split(".")[-1])


class DDMCollectionDIDType:
    """
    Data Identifier Types for DDM Collections
    """

    DATASET = "DATASET"
    CONTAINER = "CONTAINER"


class DDMCollectionState:
    """
    States for DDM Collections
    """

    open = "open"
    closed = "closed"
    missing = "missing"


class PandaTaskDataHandler(BaseDataHandler):
    """
    Handler for PanDA task intermediate/output data in the workflow.
    This class is responsible for managing the data generated by PanDA task within a workflow.
    The output data from a PanDA task is usually a DDM container, which remains open even after the task completion.
    Thus, the handler not only checks the status of the DDM collection to determine if there are files available, but also verifies the step status of source workflow steps to ensure that the data generation process has been completed successfully.
    """

    def __init__(self, *args, **kwargs):
        """
        Initialize the data handler with necessary parameters.
        """
        # Initialize base class or any required modules here
        super().__init__(*args, **kwargs)
        self.plugin_flavor = "panda_task"

    def check_target(self, data_spec: WFDataSpec, **kwargs) -> WFDataTargetCheckResult:
        """
        Check the status of the PanDA task data target.
        This method should be implemented to handle the specifics of PanDA task data status checking.

        Args:
            data_spec (WFDataSpec): The data specification containing details about the data to be checked.
            **kwargs: Additional keyword arguments that may be required for checking.

        Returns:
            WFDataTargetCheckResult: An object containing the result of the check, including success status, current data status, and message.
        """
        tmp_log = LogWrapper(logger, f"check_target workflow_id={data_spec.workflow_id} data_id={data_spec.data_id}")
        # Initialize
        check_result = WFDataTargetCheckResult()
        # Get workflow options for partial data handling
        allow_partial_inputs = DEFAULT_ALLOW_PARTIAL_INPUTS
        min_input_files = DEFAULT_MIN_INPUT_FILES
        workflow_spec = self.tbif.get_workflow(data_spec.workflow_id)
        if workflow_spec is not None:
            workflow_options = workflow_spec.definition_json_map.get("options", {})
            if workflow_options:
                allow_partial_inputs = workflow_options.get("allow_partial_inputs", DEFAULT_ALLOW_PARTIAL_INPUTS)
                min_input_files = workflow_options.get("min_input_files", DEFAULT_MIN_INPUT_FILES)
        # Check data flavor
        if data_spec.flavor != self.plugin_flavor:
            tmp_log.warning(f"flavor={data_spec.flavor} not {self.plugin_flavor}; skipped")
            check_result.message = f"flavor not {self.plugin_flavor}; skipped"
            return check_result
        # Check source step status
        if data_spec.source_step_id is not None:
            source_step_spec = self.tbif.get_workflow_step(data_spec.source_step_id)
            if source_step_spec is None:
                check_result.success = False
                check_result.message = f"Failed to get source step step_id={data_spec.source_step_id}; skipped"
                tmp_log.error(f"{check_result.message}")
                return check_result
            if source_step_spec.status == WFStepStatus.done:
                # Source step done; consider data fully available
                check_result.success = True
                check_result.check_status = WFDataTargetCheckStatus.complete
                tmp_log.info(f"Source step step_id={source_step_spec.step_id} done, data considered fully available; check_status={check_result.check_status}")
                return check_result
            elif source_step_spec.status in WFStepStatus.final_statuses:
                # Source step in final status but not done; skip data availability
                check_result.success = True
                check_result.message = f"Source step step_id={source_step_spec.step_id} {source_step_spec.status}; skip data availability check"
                tmp_log.warning(f"{check_result.message}")
                return check_result
            else:
                tmp_log.info(f"Source step step_id={source_step_spec.step_id} status={source_step_spec.status}; checking data availability")
        else:
            tmp_log.info("No source step yet; checking data availability")
        # Without source step or source step not terminated; check number of files and state of DDM collections
        total_n_files = 0
        none_exist = True
        all_existing_closed = True
        output_types = data_spec.get_parameter("output_types")
        if output_types is None:
            output_types = []
        for output_type in output_types:
            collection = f"{data_spec.target_id}_{output_type}"
            collection_meta = self.ddm_if.get_dataset_metadata(collection, ignore_missing=True, check_content_state=True)
            if collection_meta is None:
                check_result.success = False
                check_result.message = f"Failed to get metadata for collection {collection}"
                tmp_log.error(f"{check_result.message}")
                return check_result
            collection_state = collection_meta.get("state")
            collection_content_state = collection_meta.get("content_state")
            if collection_state == DDMCollectionState.missing:
                tmp_log.debug(f"Collection {collection} does not exist")
                continue
            none_exist = False
            n_files = collection_meta.get("length", 0)
            total_n_files += n_files
            if collection_state != DDMCollectionState.closed or collection_content_state == DDMCollectionState.open:
                all_existing_closed = False
            tmp_log.debug(f"Got collection {collection} n_files={n_files} state={collection_state}")
        # Check number of files and collection state
        if none_exist:
            check_result.check_status = WFDataTargetCheckStatus.nonexist
        elif all_existing_closed and total_n_files > 0:
            # All existing collections are closed and non-empty; data is complete
            check_result.check_status = WFDataTargetCheckStatus.complete
        elif allow_partial_inputs and total_n_files >= min_input_files:
            # At least min_input_files files for step input
            check_result.check_status = WFDataTargetCheckStatus.suffice
        else:
            check_result.check_status = WFDataTargetCheckStatus.insuffi
        check_result.success = True
        tmp_log.info(f"Got total_n_files={total_n_files} all_existing_closed={all_existing_closed}; check_status={check_result.check_status}")
        return check_result
