name: Flake8 Check

on: [pull_request]

jobs:
  check-flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install flake8
      run: pip install flake8

    - name: Create flake8 config on the fly
      run: |
        echo "[flake8]" > flake8.ini
        echo "ignore = E501,U100,W503,F403,F405,W605,E203" >> flake8.ini

    - name: Run flake8 on changed files
      run: |
        files=$(git diff --name-only origin/master...HEAD -- '*.py')
        if [ -n "$files" ]; then
          for file in $files; do
            if [ -f "$file" ]; then
              flake8 "$file" --config=flake8.ini
            else
              echo "File $file was deleted."
            fi
          done
        else
          echo "No Python files changed."
        fi